name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        default: prerelease
        description: Release Type
        options:
          - release
          - prerelease
      identifier:
        type: string
        default: rc
        description: Pre-Release Identifier
        required: false
      include-pre-releases:
        type: boolean
        default: true
        description: Include Pre-Releases

concurrency:
  group: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref_type != 'tag' }}

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Draft Release"
        uses: release-drafter/release-drafter@v6.1.0
        with:
          prerelease: ${{ github.event.inputs.release-type != 'release' }}
          prerelease-identifier: ${{ github.event.inputs.identifier }}
          include-pre-releases: ${{ github.event.inputs.include-pre-releases }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
